package com.example.crm.enums;

public enum AuditAction {
	SERVER_CREATED, SERVER_UPDATED, CHANNEL_CREATED, CHANNEL_DELETED, MEMBER_JOINED, MEMBER_LEFT, MEMBER_KICKED, ROLE_CHANGED, INVITE_CREATED, MESSAGE_PINNED
}
