package com.example.crm.entity;

import java.time.Instant;
import java.util.LinkedHashMap;
import java.util.LinkedHashSet;
import java.util.Map;
import java.util.Set;

import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.index.CompoundIndex;
import org.springframework.data.mongodb.core.mapping.Document;

import com.example.crm.enums.MessageType;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

// Messages Live In Their Own Collection (Not Inside Room) -> No 16MB Limit, Real Pagination
@Document(collection = "messages")
@CompoundIndex(name = "room_created", def = "{'roomId': 1, 'createdAt': -1}")
// Idempotency Key: A Client Retry With The Same clientMessageId Hits This Unique Index Instead Of
// Creating A Second Message. Partial Filter -> System Messages (No clientMessageId) Are Not Indexed.
@CompoundIndex(name = "idempotency_key", def = "{'roomId': 1, 'senderId': 1, 'clientMessageId': 1}", unique = true,
		partialFilter = "{ 'clientMessageId': { '$type': 'string' } }")
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class Message {
	@Id
	private String id;
	private String roomId;
	private String senderId;
	// Generated By The Client Once Per Message And Reused On Every Retry Of That Message
	private String clientMessageId;
	private String content;
	private MessageType type;
	private String replyToId;
	@Builder.Default
	private Set<String> mentions = new LinkedHashSet<>();
	// Emoji -> UserIds Who Reacted
	@Builder.Default
	private Map<String, Set<String>> reactions = new LinkedHashMap<>();
	private boolean edited;
	private boolean deleted;
	private boolean pinned;
	private Instant createdAt;
	private Instant editedAt;
}
